version: '3.8'

services:
  green:
    image: 276995858259.dkr.ecr.ap-northeast-2.amazonaws.com/petbulance:latest
    container_name: green
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=green
      - ENV=green
    restart: always
